Style/AsciiComments:
    Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true
Layout/SpaceAroundMethodCallOperator:
    Enabled: true
Lint/DeprecatedOpenSSLConstant:
    Enabled: true
Lint/MixedRegexpCaptureTypes:
    Enabled: true
Lint/RaiseException:
    Enabled: true
Lint/StructNewOverride:
    Enabled: true
Style/ExponentialNotation:
    Enabled: true
Style/HashEachMethods:
    Enabled: true
Style/HashTransformKeys:
    Enabled: false # Ruby 2.5
Style/HashTransformValues:
    Enabled: true
Style/RedundantFetchBlock:
    Enabled: true
Style/RedundantRegexpCharacterClass:
    Enabled: true
Style/RedundantRegexpEscape:
    Enabled: true
Style/SlicingWithRange:
    Enabled: false # Ruby 2.6
